# Generated by Django 4.2.30 on 2026-09-06 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('gaming', 'Игры'), ('media', 'Музыка/Кино'), ('soft', 'Софт/Учеба'), ('other', 'Другое')], max_length=50, verbose_name='Категория')),
                ('price', models.IntegerField(verbose_name='Цена в месяц (грн)')),
                ('billing_date', models.DateField(verbose_name='Дата списания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма (грн)')),
                ('paid_date', models.DateField(verbose_name='Дата оплаты')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-paid_date'],
            },
        ),
    ]
